import Link from "next/link";
import { Footer } from "@/components/shared/footer";
import { PublicNav } from "@/components/shared/public-nav";
import { publicMetadata } from "@/lib/seo";

export const metadata = publicMetadata({ title: "How it works", description: "How V3l0city’s browser dashboard records, stores, restores, and shares driving data.", path: "/how-it-works" });

export default function HowItWorksPage() {
  return <div className="site-shell"><PublicNav /><main id="main-content"><section className="legal-hero"><div className="container"><span className="eyebrow">How it works</span><h1 className="display heading-xl">A deliberate<br /><span className="accent">data path.</span></h1><p className="copy">V3l0city separates recording, storage, restore, and social visibility so you can understand what happens at each step.</p></div></section><section className="section"><div className="container process-list"><article><span>01</span><div><h2>Start manually on a phone</h2><p>On a compatible mobile browser, select Start and grant location access. V3l0city derives speed and distance while the page stays open, visible, and unlocked.</p></div></article><article><span>02</span><div><h2>Keep a local trip library</h2><p>Completed trips and derived samples are saved to the separate IndexedDB database in that browser. Exact route coordinates are not persisted.</p></div></article><article><span>03</span><div><h2>Enable cloud backup only if you choose</h2><p>When online backup is on, completed trips can be restored into another browser after you sign in. Sync state remains visible, and unsynced data stays local until it succeeds.</p></div></article><article><span>04</span><div><h2>Review, control, or delete</h2><p>Desktop is read-only for driving data. Use your account settings to update visibility, export browser data, remove browser data, or permanently delete your account.</p></div></article></div></section><section className="section-tight"><div className="container cta-panel panel"><div><h2 className="display heading-md">The browser has a clear boundary.</h2><p className="copy">It does not offer background tracking, auto-start, native widgets, or push setup.</p></div><Link href="/safety" className="button button-secondary">Read safety guidance</Link></div></section></main><Footer /></div>;
}
