"use client";

import { FormEvent, useEffect, useState } from "react";

import { useApp } from "@/components/app/app-provider";
import { createClient } from "@/lib/supabase/client";
import type { FriendProfile } from "@/lib/types";

type FriendRequests = { incoming: FriendProfile[]; outgoing: FriendProfile[]; friends: FriendProfile[] };
const invoke = async <T,>(name: string, body: object) => { const supabase = createClient(); if (!supabase) throw new Error("Cloud features are not configured."); const { data, error } = await supabase.functions.invoke<T>(name, { body }); if (error) throw error; return data; };

export function Friends() {
  const { profile } = useApp();
  const [requests, setRequests] = useState<FriendRequests>({ incoming: [], outgoing: [], friends: [] });
  const [query, setQuery] = useState(""); const [results, setResults] = useState<FriendProfile[]>([]); const [message, setMessage] = useState<string | null>(null); const [reporting, setReporting] = useState<FriendProfile | null>(null); const [reportReason, setReportReason] = useState("harassment");
  const load = async () => { try { setRequests((await invoke<FriendRequests>("friend-requests", {})) ?? { incoming: [], outgoing: [], friends: [] }); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not load friend requests."); } };
  useEffect(() => {
    let active = true;
    void invoke<FriendRequests>("friend-requests", {}).then((data) => { if (active) setRequests(data ?? { incoming: [], outgoing: [], friends: [] }); }).catch((caught: unknown) => { if (active) setMessage(caught instanceof Error ? caught.message : "Could not load friend requests."); });
    return () => { active = false; };
  }, []);
  async function search(event: FormEvent) { event.preventDefault(); if (query.trim().length < 2) return; try { const data = await invoke<{ users: FriendProfile[] }>("search-friends", { query }); setResults(data?.users ?? []); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not search profiles."); } }
  async function respond(userId: string, action: "accept" | "decline" | "cancel" | "remove" | "block") { try { await invoke("friend-respond", { userId, action }); await load(); setResults((current) => current.filter((result) => action !== "block" || result.userId !== userId)); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not update this relationship."); } }
  async function request(userId: string) { try { await invoke("friend-request", { userId }); setMessage("Friend request sent."); await load(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not send the friend request."); } }
  async function report(event: FormEvent) { event.preventDefault(); if (!reporting) return; try { await invoke("report-profile", { targetUserId: reporting.userId, reason: reportReason }); setMessage("Thanks. Your report was received for review."); setReporting(null); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not submit this report."); } }
  const userCard = (person: FriendProfile, mode: "search" | "incoming" | "outgoing" | "friend") => <div className="social-row" key={person.userId}><div className="avatar">{person.displayName.slice(0, 1).toUpperCase()}</div><div><strong>{person.displayName}</strong><span>@{person.username}</span></div><div className="social-actions">{mode === "search" && person.relationship === "none" && <button className="button button-secondary button-small" onClick={() => void request(person.userId)}>Add friend</button>}{mode === "incoming" && <><button className="button button-primary button-small" onClick={() => void respond(person.userId, "accept")}>Accept</button><button className="button button-secondary button-small" onClick={() => void respond(person.userId, "decline")}>Decline</button></>}{mode === "outgoing" && <button className="button button-secondary button-small" onClick={() => void respond(person.userId, "cancel")}>Cancel request</button>}{mode === "friend" && <><button className="button button-secondary button-small" onClick={() => void respond(person.userId, "remove")}>Remove</button><button className="text-button" onClick={() => setReporting(person)}>Report</button><button className="text-button danger-text" onClick={() => void respond(person.userId, "block")}>Block</button></>}</div></div>;
  return <div className="container"><div className="page-heading"><div><span className="eyebrow">Opt-in social</span><h1 className="display heading-lg">Friends, with boundaries.</h1><p className="copy">Profiles are discoverable only to signed-in users. Your leaderboard and nearby choices remain separate and off by default.</p></div></div>{!profile?.leaderboardOptIn && <div className="notice"><span>!</span><div><strong>Your leaderboard visibility is off.</strong> You can still add friends; enable leaderboard visibility in Account only if you want your aggregate statistics included.</div></div>}{message && <p className="form-success social-message">{message}</p>}<div className="social-grid"><section className="social-panel panel"><h2 className="display heading-md">Find people</h2><form className="social-search" onSubmit={search}><input className="input" value={query} placeholder="Search username or display name" minLength={2} onChange={(event) => setQuery(event.target.value)} /><button className="button button-primary button-small">Search</button></form><div className="list social-list">{results.length ? results.map((person) => userCard(person, "search")) : <p className="muted">Search for a username or display name to send a request.</p>}</div></section><section className="social-panel panel"><h2 className="display heading-md">Your circle</h2>{requests.incoming.length > 0 && <div className="request-group"><h3>Incoming</h3>{requests.incoming.map((person) => userCard(person, "incoming"))}</div>}{requests.outgoing.length > 0 && <div className="request-group"><h3>Sent</h3>{requests.outgoing.map((person) => userCard(person, "outgoing"))}</div>}<div className="request-group"><h3>Friends</h3>{requests.friends.length ? requests.friends.map((person) => userCard(person, "friend")) : <p className="muted">No accepted friends yet.</p>}</div></section></div>{reporting && <div className="modal-backdrop" role="presentation"><form className="modal panel" onSubmit={report}><h2 className="display heading-md">Report {reporting.displayName}</h2><p>Use reports for harassment, impersonation, unsafe driving encouragement, or other policy concerns. Do not use this for emergencies.</p><div className="field"><label htmlFor="reason">Reason</label><select className="select" id="reason" value={reportReason} onChange={(event) => setReportReason(event.target.value)}><option value="harassment">Harassment or hateful profile</option><option value="impersonation">Impersonation</option><option value="unsafe_driving">Unsafe-driving encouragement</option><option value="other">Other policy concern</option></select></div><div className="button-row"><button className="button button-primary">Send report</button><button type="button" className="button button-secondary" onClick={() => setReporting(null)}>Cancel</button></div></form></div>}</div>;
}
