"use client";

import { useEffect, useState } from "react";

import { createClient } from "@/lib/supabase/client";
import { distanceLabel, speedLabel } from "@/lib/format";
import type { LeaderboardEntry } from "@/lib/types";

const labels = { distance: "Distance", average_speed: "Average speed", max_speed: "Maximum speed", trip_count: "Trip count" } as const;

export function Leaderboards() {
  const [scope, setScope] = useState<LeaderboardEntry["scope"]>("friends"); const [metric, setMetric] = useState<LeaderboardEntry["metric"]>("distance"); const [period, setPeriod] = useState<LeaderboardEntry["period"]>("week"); const [entries, setEntries] = useState<LeaderboardEntry[]>([]); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { const load = async () => { try { const supabase = createClient(); if (!supabase) throw new Error("Cloud features are not configured."); const { data, error } = await supabase.functions.invoke<{ entries: LeaderboardEntry[] }>("leaderboards", { body: { scope, metric, period } }); if (error) throw error; setEntries(data?.entries ?? []); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not load the leaderboard."); } }; void load(); }, [scope, metric, period]);
  const value = (entry: LeaderboardEntry) => entry.metric === "distance" ? distanceLabel(entry.value) : entry.metric === "trip_count" ? `${entry.value} trips` : speedLabel(entry.value);
  return <div className="container"><div className="page-heading"><div><span className="eyebrow">Aggregate statistics</span><h1 className="display heading-lg">Leaderboards without the pressure.</h1><p className="copy">These are opt-in, non-real-time personal statistics—not a challenge, safety score, or reason to drive faster.</p></div></div><div className="notice"><span>!</span><div><strong>Use while parked.</strong> Leaderboard values are retrospective aggregates and can be delayed or affected by recording gaps. Never interact with V3l0city while driving.</div></div><div className="leader-controls panel"><div className="field"><label htmlFor="scope">Scope</label><select className="select" id="scope" value={scope} onChange={(event) => setScope(event.target.value as typeof scope)}><option value="friends">Friends</option><option value="global">Global</option><option value="nearby">Nearby</option></select></div><div className="field"><label htmlFor="metric">Metric</label><select className="select" id="metric" value={metric} onChange={(event) => setMetric(event.target.value as typeof metric)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="field"><label htmlFor="period">Period</label><select className="select" id="period" value={period} onChange={(event) => setPeriod(event.target.value as typeof period)}><option value="week">This week</option><option value="month">This month</option><option value="all_time">All time</option></select></div></div>{message && <p className="form-error">{message}</p>}<div className="leader-list panel">{entries.length ? entries.map((entry) => <div className="leader-row" key={entry.userId}><strong className="rank">{String(entry.rank).padStart(2, "0")}</strong><div><strong>{entry.displayName}</strong><span>@{entry.username}</span></div><b>{value(entry)}</b></div>) : <div className="empty-state"><h2 className="display heading-md">Nothing to show yet.</h2><p>This scope has no eligible opt-in aggregate data for the selected period.</p></div>}</div></div>;
}
