import { ContactLine, LegalPage } from "@/components/marketing/legal-page";
import { appConfig } from "@/lib/config";
import { publicMetadata } from "@/lib/seo";

export const metadata = publicMetadata({ title: "Privacy notice", description: "How V3l0city collects, uses, stores, and protects personal information.", path: "/privacy" });

export default function PrivacyPage() {
  return <LegalPage title={<>Privacy<br /><span className="accent">notice.</span></>} intro="This notice explains how V3l0city handles personal information for the public website and web dashboard. It must be reviewed and finalized by qualified counsel before production launch." sections={[
    { title: "Who controls your information", content: <><p>{appConfig.legalEntityName} is the controller for the personal information described here. This notice applies to the V3l0city website, browser dashboard, and related support interactions.</p><ContactLine /></> },
    { title: "Information we collect", content: <ul><li><strong>Account information:</strong> email address, username, display name, and authentication/session data.</li><li><strong>Trip information:</strong> started/ended time, distance, derived speed samples, and trip summaries. The web app does not persist raw route coordinates.</li><li><strong>Privacy choices:</strong> online-backup, leaderboard, nearby-discovery, legal-acceptance, and cookie-consent choices.</li><li><strong>Optional nearby data:</strong> a coarse area cell only when you deliberately enable nearby discovery; it is not an exact location or route.</li><li><strong>Technical information:</strong> browser storage, security/audit records, and consent-gated aggregate site analytics.</li></ul> },
    { title: "Why we use it", content: <ul><li>Provide authentication, profile settings, browser trip storage, optional cloud restore, and support.</li><li>Operate opt-in friends and leaderboards and prevent abuse.</li><li>Protect the service, investigate security issues, honor legal obligations, and enforce our terms.</li><li>Measure site usage only after analytics consent. We do not use advertising pixels, fingerprinting, session replay, or trip/location analytics.</li></ul> },
    { title: "Legal bases and choices", content: <p>Where applicable, we process account and requested product features to perform our contract with you; security and service improvement for legitimate interests; and optional analytics, nearby discovery, and similar features based on your choice. You can change nonessential choices in your account or cookie settings. This language requires jurisdiction-specific legal review before launch.</p> },
    { title: "Sharing and international transfers", content: <p>We use service providers to host the website and application data, including Vercel and Supabase, plus Cloudflare Turnstile if enabled. Providers process data only to provide their services. Data may be processed outside your country; production launch requires appropriate transfer safeguards and vendor agreements where required.</p> },
    { title: "Retention and deletion", content: <p>Browser data remains in the browser until you clear it. Cloud account data remains while your account is active, then is removed through self-service account deletion subject to limited security, backup, and legal-retention periods that must be finalized in the production retention schedule. We do not sell personal information or use it for cross-context behavioral advertising.</p> },
    { title: "Your rights", content: <p>Depending on where you live, you may have rights to access, correct, delete, export, restrict, object to, or withdraw consent for some processing. Use account controls for common requests, or contact us. You may also have a right to complain to a relevant supervisory authority. We do not discriminate for exercising privacy rights.</p> },
    { title: "Children and updates", content: <p>V3l0city is not for people under 16. We do not knowingly collect personal information from children under 16. We will update this notice when our practices change and record a new effective date and version.</p> },
  ]} />;
}
